import { useEffect, useMemo, useState } from 'react'
import './App.css'
import { products as demoProducts, storeInfo } from './data'
import type { CartItem, CategorySlug, Product, ProductVariant } from './types'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
const money = (value: number) => `${new Intl.NumberFormat('ru-RU').format(value)} ₽`

function go(path: string) {
  window.history.pushState({}, '', path)
  window.dispatchEvent(new PopStateEvent('popstate'))
  window.scrollTo({ top: 0, behavior: 'smooth' })
}

function Icon({ name }: { name: 'search'|'heart'|'bag'|'menu'|'close'|'pin'|'arrow' }) {
  const paths = {
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    heart: <path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/>,
    bag: <><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,
    menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>,
    close: <path d="m6 6 12 12M18 6 6 18"/>,
    pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
    arrow: <path d="M5 12h14m-5-5 5 5-5 5"/>,
  }
  return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

function Header({ cartCount, favoriteCount, onCart }: { cartCount:number; favoriteCount:number; onCart:()=>void }) {
  const [menu, setMenu] = useState(false)
  return <>
    <div className="topline"><span>Натуральные вещи из Монголии</span><button onClick={() => go('/store')}><Icon name="pin"/> Офлайн-магазин · Улан-Удэ</button></div>
    <header className="header container">
      <button className="mobile-menu" onClick={() => setMenu(!menu)} aria-label="Открыть меню"><Icon name={menu ? 'close' : 'menu'}/></button>
      <button className="logo" onClick={() => go('/')}><span className="logo-mark">ᠮ</span><span><b>НАРАН</b><small>тепло из Монголии</small></span></button>
      <nav className={menu ? 'open' : ''} onClick={() => setMenu(false)}>
        <button onClick={() => go('/catalog')}>Каталог</button><a href="/#materials">Материалы</a><button onClick={() => go('/catalog?category=gifts')}>Подарки</button><button onClick={() => go('/store')}>О магазине</button><a href="#delivery">Доставка</a>
      </nav>
      <div className="header-actions"><button aria-label="Поиск" onClick={() => go('/catalog?focus=search')}><Icon name="search"/></button><button aria-label="Избранное" onClick={() => go('/favorites')}><Icon name="heart"/>{favoriteCount > 0 && <i>{favoriteCount}</i>}</button><button aria-label="Корзина" onClick={onCart}><Icon name="bag"/>{cartCount > 0 && <i>{cartCount}</i>}</button></div>
    </header>
  </>
}

function Ornament() { return <div className="ornament" aria-hidden="true"><span>◇</span><i/><span>◇</span><i/><span>◇</span></div> }

function ProductCard({ product, favorite, onFavorite }: { product:Product; favorite:boolean; onFavorite:(id:number)=>void }) {
  const offline = product.variants.some(v => v.offline_stock_quantity > 0)
  return <article className="product-card">
    <button className="product-photo" onClick={() => go(`/product/${product.slug}`)}><img src={product.images[0].url} alt={product.images[0].alt} loading="lazy"/>{product.is_new && <span className="tag">Новинка</span>}<span className={`stock-dot ${offline ? '' : 'muted'}`}>{offline ? 'Есть в магазине' : 'Только онлайн'}</span></button>
    <button className={`favorite ${favorite ? 'active' : ''}`} onClick={() => onFavorite(product.id)} aria-label="Добавить в избранное"><Icon name="heart"/></button>
    <button className="product-copy" onClick={() => go(`/product/${product.slug}`)}><span>{product.material}</span><h3>{product.name}</h3><p>{product.short_description}</p><strong>{money(Math.min(...product.variants.map(v => v.price)))}</strong></button>
  </article>
}

const categories: { slug:CategorySlug; name:string; subtitle:string; image:string }[] = [
  { slug:'clothing', name:'Одежда', subtitle:'Кашемир, як и верблюжья шерсть', image:'https://images.unsplash.com/photo-1608234807905-4466023792f5?auto=format&fit=crop&w=900&q=84' },
  { slug:'accessories', name:'Аксессуары', subtitle:'Тёплые детали на каждый день', image:'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=84' },
  { slug:'home', name:'Для дома', subtitle:'Фактура и спокойствие', image:'https://images.unsplash.com/photo-1583845112203-454c2254ed0e?auto=format&fit=crop&w=900&q=84' },
  { slug:'gifts', name:'Подарки', subtitle:'Готовые решения с теплом', image:'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=900&q=84' },
]

function Home({ products, favorites, onFavorite }: { products:Product[]; favorites:Set<number>; onFavorite:(id:number)=>void }) {
  return <main>
    <section className="hero container"><div className="hero-copy"><p className="kicker">Натуральные материалы · Монголия</p><h1>Тепло<br/><em>из Монголии</em></h1><p>Кашемир, шерсть яка и верблюжья шерсть — отобранные вещи для сибирской зимы, дома и подарков.</p><div className="hero-buttons"><button className="button dark" onClick={() => go('/catalog')}>Смотреть каталог <Icon name="arrow"/></button><button className="button light" onClick={() => go('/store')}>Посетить магазин</button></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1600&q=88" alt="Натуральная одежда из Монголии"/><div className="hero-label">Улан-Удэ<br/><b>Можно примерить</b></div></div></section>
    <section className="benefits container"><div><span>01</span><h3>Отбираем в Монголии</h3><p>Работаем с производителями и проверяем состав.</p></div><div><span>02</span><h3>Можно примерить</h3><p>Показываем остаток в офлайн-магазине.</p></div><div><span>03</span><h3>Доставляем по России</h3><p>Надёжно упаковываем и отправляем с отслеживанием.</p></div></section>
    <section className="section container"><div className="section-head"><div><p className="kicker">Выберите направление</p><h2>Категории</h2></div><button className="text-link" onClick={() => go('/catalog')}>Весь каталог <Icon name="arrow"/></button></div><div className="category-grid">{categories.map(c => <button className="category-card" key={c.slug} onClick={() => go(`/catalog?category=${c.slug}`)}><img src={c.image} alt="" loading="lazy"/><span><b>{c.name}</b><small>{c.subtitle}</small></span><Icon name="arrow"/></button>)}</div></section>
    <section className="section new-section"><div className="container"><div className="section-head"><div><p className="kicker">Новая поставка</p><h2>Новинки</h2></div><button className="text-link" onClick={() => go('/catalog')}>Смотреть все <Icon name="arrow"/></button></div><div className="product-grid">{products.filter(p => p.is_new).map(p => <ProductCard key={p.id} product={p} favorite={favorites.has(p.id)} onFavorite={onFavorite}/>)}</div></div></section>
    <section className="section materials container" id="materials"><div className="materials-intro"><p className="kicker">Гид по материалам</p><h2>Как выбрать своё тепло</h2><p>Материалы отличаются ощущением, плотностью и характером. Сравните и найдите тот, который подходит именно вам.</p><Ornament/></div><div className="material-table"><div className="material-row heading"><span>Материал</span><span>Ощущение</span><span>Тепло</span><span>Лучше всего</span></div><div className="material-row"><b>Кашемир</b><span>Невесомый, мягкий</span><span>●●●○</span><span>На каждый день</span></div><div className="material-row"><b>Шерсть яка</b><span>Плотная, фактурная</span><span>●●●●</span><span>Для сильных морозов</span></div><div className="material-row"><b>Верблюжья</b><span>Сухое природное тепло</span><span>●●●●</span><span>Дом и верхняя одежда</span></div><div className="material-row"><b>Овечья</b><span>Упругая, традиционная</span><span>●●●○</span><span>Аксессуары</span></div></div></section>
    <section className="gift-banner container"><img src="https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=1400&q=84" alt="Подарочный набор" loading="lazy"/><div><p className="kicker">Готовые решения</p><h2>Подарки, в которых есть забота</h2><p>Соберём комплект, добавим открытку и аккуратно упакуем.</p><button className="button dark" onClick={() => go('/catalog?category=gifts')}>Выбрать подарок <Icon name="arrow"/></button></div></section>
    <StorePreview/>
    <section className="section reviews container"><div className="section-head"><div><p className="kicker">Отзывы покупателей</p><h2>За что нас выбирают</h2></div></div><div className="review-grid"><blockquote>«Очень мягкий кашемир, совсем не колется. Смогла сначала примерить в магазине и спокойно выбрать цвет.»<footer>Дарима · Улан-Удэ</footer></blockquote><blockquote>«Плед оказался действительно тёплым и лёгким. Упаковка красивая — можно сразу дарить.»<footer>Елена · Иркутск</footer></blockquote><blockquote>«Подсказали точные замеры в сообщениях и быстро отправили. Размер подошёл.»<footer>Анна · Чита</footer></blockquote></div></section>
    <Newsletter/>
  </main>
}

function Catalog({ products, favorites, onFavorite, favoritesOnly=false }: { products:Product[]; favorites:Set<number>; onFavorite:(id:number)=>void; favoritesOnly?:boolean }) {
  const params = new URLSearchParams(window.location.search)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState(params.get('category') || 'all')
  const [material, setMaterial] = useState('all')
  const [offline, setOffline] = useState(false)
  const [sort, setSort] = useState('popular')
  const filtered = useMemo(() => products.filter(p => (!favoritesOnly || favorites.has(p.id)) && (category === 'all' || p.category.slug === category) && (material === 'all' || p.material === material) && (!offline || p.variants.some(v => v.offline_stock_quantity > 0)) && (`${p.name} ${p.material}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b) => sort === 'price-asc' ? a.variants[0].price-b.variants[0].price : sort === 'price-desc' ? b.variants[0].price-a.variants[0].price : Number(b.is_new)-Number(a.is_new)), [products,favoritesOnly,favorites,category,material,offline,search,sort])
  return <main className="catalog-page container"><div className="breadcrumbs"><button onClick={() => go('/')}>Главная</button><span>/</span><span>{favoritesOnly ? 'Избранное' : 'Каталог'}</span></div><div className="catalog-title"><div><p className="kicker">Коллекция</p><h1>{favoritesOnly ? 'Избранное' : 'Каталог'}</h1><p>{favoritesOnly ? 'Сохранённые вещи, к которым можно вернуться.' : 'Натуральные вещи из Монголии с актуальным наличием онлайн и в магазине.'}</p></div><span>{filtered.length} товаров</span></div>
    <div className="catalog-tools"><label className="search"><Icon name="search"/><input autoFocus={params.has('focus')} value={search} onChange={e => setSearch(e.target.value)} placeholder="Найти кашемир, плед, подарок…"/></label><select value={sort} onChange={e => setSort(e.target.value)}><option value="popular">Сначала популярные</option><option value="price-asc">Сначала дешевле</option><option value="price-desc">Сначала дороже</option></select></div>
    <div className="catalog-layout"><aside><fieldset><legend>Категория</legend>{[['all','Все категории'],...categories.map(c => [c.slug,c.name])].map(([v,n]) => <label key={v}><input type="radio" name="category" value={v} checked={category===v} onChange={() => setCategory(v)}/><span>{n}</span></label>)}</fieldset><fieldset><legend>Материал</legend>{['all','Кашемир','Шерсть яка','Верблюжья шерсть','Овечья шерсть'].map(v => <label key={v}><input type="radio" name="material" checked={material===v} onChange={() => setMaterial(v)}/><span>{v==='all'?'Все материалы':v}</span></label>)}</fieldset><label className="switch"><input type="checkbox" checked={offline} onChange={e => setOffline(e.target.checked)}/><i/><span>Есть в офлайн-магазине</span></label></aside><div>{filtered.length ? <div className="product-grid catalog-products">{filtered.map(p => <ProductCard key={p.id} product={p} favorite={favorites.has(p.id)} onFavorite={onFavorite}/>)}</div> : <div className="empty-state"><span>◇</span><h2>Ничего не найдено</h2><p>Попробуйте изменить фильтры или поисковый запрос.</p><button className="button dark" onClick={() => {setSearch('');setCategory('all');setMaterial('all');setOffline(false)}}>Сбросить фильтры</button></div>}</div></div>
  </main>
}

function ProductPage({ product, favorite, onFavorite, onAdd }: { product:Product; favorite:boolean; onFavorite:(id:number)=>void; onAdd:(p:Product,v:ProductVariant)=>void }) {
  const [imageIndex,setImageIndex]=useState(0), [color,setColor]=useState(product.variants[0].color), [size,setSize]=useState(product.variants[0].size), [tab,setTab]=useState('details')
  const variant=product.variants.find(v=>v.color===color&&v.size===size) || product.variants[0]
  useEffect(() => { document.title=`${product.name} — Наран`; const script=document.createElement('script'); script.type='application/ld+json'; script.text=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:product.name,image:product.images.map(i=>i.url),description:product.short_description,sku:variant.sku,brand:{'@type':'Brand',name:product.brand},offers:{'@type':'Offer',price:variant.price,priceCurrency:'RUB',availability:variant.online_stock_quantity?'https://schema.org/InStock':'https://schema.org/OutOfStock'}}); document.head.appendChild(script); return()=>script.remove() },[product,variant])
  const sizes=[...new Set(product.variants.filter(v=>v.color===color).map(v=>v.size))], colors=[...new Set(product.variants.map(v=>v.color))]
  return <main className="product-page container"><div className="breadcrumbs"><button onClick={()=>go('/')}>Главная</button><span>/</span><button onClick={()=>go(`/catalog?category=${product.category.slug}`)}>{product.category.name}</button><span>/</span><span>{product.name}</span></div><div className="product-layout"><div className="gallery"><div className="thumbnails">{product.images.map((img,i)=><button className={i===imageIndex?'active':''} onClick={()=>setImageIndex(i)} key={img.url}><img src={img.url} alt=""/></button>)}</div><div className="main-image"><img src={product.images[imageIndex].url} alt={product.images[imageIndex].alt}/>{product.is_new&&<span className="tag">Новинка</span>}</div></div><div className="product-info"><p className="kicker">{product.material} · {product.country_of_origin}</p><h1>{product.name}</h1><p className="product-lead">{product.short_description}</p><div className="price"><strong>{money(variant.price)}</strong>{variant.compare_at_price&&<s>{money(variant.compare_at_price)}</s>}</div><div className="choice"><label>Цвет: <b>{color}</b></label><div>{colors.map(c=><button className={c===color?'active':''} onClick={()=>{setColor(c);setSize(product.variants.find(v=>v.color===c)!.size)}} key={c}>{c}</button>)}</div></div><div className="choice"><label>Размер: <b>{size}</b><button className="size-guide" onClick={()=>setTab('measurements')}>Таблица размеров</button></label><div>{sizes.map(s=><button className={s===size?'active':''} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div></div><div className="availability"><p><i/> Онлайн: {variant.online_stock_quantity > 0 ? `в наличии · ${variant.online_stock_quantity} шт.` : 'нет в наличии'}</p><p><i/> В магазине: {variant.offline_stock_quantity > 0 ? `можно примерить · ${variant.offline_stock_quantity} шт.` : 'уточните поступление'}</p></div><button className="button terracotta wide" onClick={()=>onAdd(product,variant)}>Добавить в корзину · {money(variant.price)}</button><div className="secondary-actions"><button onClick={()=>alert('Подключим мессенджер после получения контакта магазина.')}>Уточнить размер</button><button onClick={()=>go('/store')}>Посмотреть в магазине</button><button className={favorite?'active':''} onClick={()=>onFavorite(product.id)}><Icon name="heart"/></button></div><div className="delivery-note"><b>Доставка по России</b><span>Срок и стоимость рассчитаем при оформлении</span></div></div></div>
    <section className="product-tabs"><div className="tab-buttons">{[['details','Описание'],['measurements','Замеры'],['care','Уход и доставка']].map(([v,n])=><button className={tab===v?'active':''} onClick={()=>setTab(v)} key={v}>{n}</button>)}</div>{tab==='details'&&<div className="tab-content"><div><h2>О вещи</h2><p>{product.description}</p><p><b>Состав:</b> {product.composition}</p><p><b>Производитель:</b> {product.manufacturer}</p></div><ul>{product.properties.map(p=><li key={p}>{p}</li>)}</ul></div>}{tab==='measurements'&&<div className="measurements"><p>{product.model_info}</p><table><thead><tr><th>Размер</th><th>Обхват груди</th><th>Длина</th><th>Рукав</th></tr></thead><tbody>{Object.entries(product.measurements).map(([s,m])=><tr key={s}><th>{s}</th><td>{m['Обхват груди']}</td><td>{m['Длина изделия']}</td><td>{m['Длина рукава']}</td></tr>)}</tbody></table></div>}{tab==='care'&&<div className="tab-content"><div><h2>Как ухаживать</h2><p>{product.care}</p></div><div><h2>Доставка и возврат</h2><p>Отправляем по России. Вернуть товар надлежащего качества можно в установленный законом срок при сохранении вида и ярлыков.</p></div></div>}</section>
    <section className="qr-card"><div className="fake-qr" aria-label="QR-код товара">{Array.from({length:64}).map((_,i)=><i className={(i*7+i%5)%3===0?'dark':''} key={i}/>)}</div><div><p className="kicker">Для офлайн-ценника</p><h2>QR-код карточки товара</h2><p>Покупатель сможет открыть состав, замеры и наличие прямо у вешалки.</p></div></section>
  </main>
}

function StorePreview() { return <section className="store-preview"><div className="container"><div className="store-photo"><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=84" alt="Интерьер офлайн-магазина — референс" loading="lazy"/><span>Фото пространства будет добавлено после открытия</span></div><div className="store-copy"><p className="kicker">Офлайн-магазин · Улан-Удэ</p><h2>Примерьте и почувствуйте материал</h2><p>В магазине можно сравнить кашемир, шерсть яка и верблюжью шерсть, подобрать размер и собрать подарок.</p><dl><div><dt>Адрес</dt><dd>{storeInfo.address}</dd></div><div><dt>Режим работы</dt><dd>{storeInfo.hours}</dd></div></dl><button className="button dark" onClick={()=>go('/store')}>Подробнее о магазине <Icon name="arrow"/></button></div></div></section> }

function StorePage() { return <main><section className="store-hero container"><div><p className="kicker">Офлайн-точка</p><h1>Магазин<br/>в Улан-Удэ</h1><p>Место, где можно не спеша потрогать материалы, сравнить оттенки и подобрать размер.</p><div className="store-facts"><div><small>Адрес</small><b>{storeInfo.address}</b></div><div><small>Режим работы</small><b>{storeInfo.hours}</b></div><div><small>Контакты</small><b>Будут добавлены перед открытием</b></div></div></div><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=85" alt="Референс интерьера магазина"/></section><section className="map-section container"><div className="map-placeholder"><Icon name="pin"/><b>Карта появится после утверждения адреса</b><span>Подключим Яндекс Карты и кнопку построения маршрута.</span></div><div><p className="kicker">Перед визитом</p><h2>Уточните размер</h2><p>У каждого товара в каталоге показан остаток в офлайн-точке. Если нужный размер остался в одном экземпляре, его можно будет зарезервировать без регистрации.</p><button className="button terracotta" onClick={()=>go('/catalog')}>Проверить наличие</button></div></section><section className="section container"><div className="section-head"><div><p className="kicker">Пространство</p><h2>Спокойно и тактильно</h2></div></div><div className="interior-grid"><img src="https://images.unsplash.com/photo-1604176354204-9268737828e4?auto=format&fit=crop&w=900&q=84" alt="Референс зоны одежды"/><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=84" alt="Референс зоны консультации"/><img src="https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=900&q=84" alt="Референс выкладки аксессуаров"/></div><p className="photo-disclaimer">Сейчас используются референсы. После готовности точки заменим их реальными фотографиями пространства.</p></section><Newsletter/></main> }

function Newsletter() { return <section className="newsletter"><div className="container"><div><p className="kicker">Письма без лишнего шума</p><h2>Новые поставки и истории материалов</h2></div><form onSubmit={e=>{e.preventDefault();alert('Форма подписки будет подключена к сервису рассылок.')}}><label><span className="sr-only">Электронная почта</span><input type="email" required placeholder="Ваш e-mail"/><button type="submit"><Icon name="arrow"/></button></label><small>Нажимая кнопку, вы соглашаетесь с обработкой персональных данных.</small></form></div></section> }

function CartDrawer({ cart, open, onClose, onChange }: { cart:CartItem[]; open:boolean; onClose:()=>void; onChange:(id:number,d:number)=>void }) { const total=cart.reduce((s,i)=>s+i.variant.price*i.quantity,0); return <div className={`drawer-layer ${open?'open':''}`} onMouseDown={onClose}><aside className="cart-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="kicker">Ваш выбор</p><h2>Корзина</h2></div><button onClick={onClose}><Icon name="close"/></button></div>{!cart.length?<div className="empty-cart"><span>◇</span><h3>Корзина пуста</h3><p>В каталоге уже есть вещи для зимы, дома и подарков.</p><button className="button dark" onClick={()=>{onClose();go('/catalog')}}>Перейти в каталог</button></div>:<><div className="cart-list">{cart.map(i=><article key={i.variant.id}><img src={i.product.images[0].url} alt=""/><div><h3>{i.product.name}</h3><p>{i.variant.color} · {i.variant.size}</p><strong>{money(i.variant.price)}</strong><div className="qty"><button onClick={()=>onChange(i.variant.id,-1)}>−</button><span>{i.quantity}</span><button onClick={()=>onChange(i.variant.id,1)}>+</button></div></div></article>)}</div><div className="cart-summary"><span>Итого</span><strong>{money(total)}</strong></div><button className="button terracotta wide" onClick={()=>alert('На следующем этапе подключим страницу оформления и оплату.')}>Оформить заказ</button><small>Наличие подтвердим перед оплатой</small></>}</aside></div> }

function Footer() { return <footer className="footer" id="delivery"><div className="container footer-grid"><div><button className="logo light-logo" onClick={()=>go('/')}><span className="logo-mark">ᠮ</span><span><b>НАРАН</b><small>тепло из Монголии</small></span></button><p>Натуральные вещи для холодного климата, дома и тёплых подарков.</p></div><div><b>Покупателям</b><button onClick={()=>go('/catalog')}>Каталог</button><button onClick={()=>go('/store')}>Офлайн-магазин</button><a href="#delivery">Доставка и возврат</a></div><div><b>Информация</b><a href="/#materials">Материалы</a><button onClick={()=>go('/store')}>О магазине</button><span>Политика конфиденциальности</span></div><div><b>Контакты</b><span>Улан-Удэ</span><span>{storeInfo.address}</span><span>{storeInfo.hours}</span></div></div><div className="container footer-bottom"><span>© 2026 Наран</span><span>Название и контакты будут уточнены перед запуском</span></div></footer> }

function App() {
  const [path,setPath]=useState(window.location.pathname), [products,setProducts]=useState<Product[]>(demoProducts), [cart,setCart]=useState<CartItem[]>(()=>JSON.parse(localStorage.getItem('naran-cart')||'[]')), [favorites,setFavorites]=useState<Set<number>>(()=>new Set(JSON.parse(localStorage.getItem('naran-favorites')||'[]'))), [cartOpen,setCartOpen]=useState(false)
  useEffect(()=>{const h=()=>setPath(window.location.pathname);window.addEventListener('popstate',h);return()=>window.removeEventListener('popstate',h)},[])
  useEffect(()=>{fetch(`${API_URL}/products?per_page=48`).then(r=>r.ok?r.json():Promise.reject()).then(d=>d.data?.length&&setProducts(d.data)).catch(()=>{})},[])
  useEffect(()=>localStorage.setItem('naran-cart',JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem('naran-favorites',JSON.stringify([...favorites])),[favorites])
  useEffect(()=>{if(!path.startsWith('/product/')) document.title=path==='/catalog'?'Каталог — Наран':path==='/store'?'Магазин в Улан-Удэ — Наран':'Наран — тепло из Монголии'},[path])
  const favorite=(id:number)=>setFavorites(current=>{const next=new Set(current);if(next.has(id)){next.delete(id)}else{next.add(id)}return next})
  const add=(product:Product,variant:ProductVariant)=>{setCart(current=>{const found=current.find(i=>i.variant.id===variant.id);return found?current.map(i=>i.variant.id===variant.id?{...i,quantity:Math.min(i.quantity+1,variant.online_stock_quantity)}:i):[...current,{product,variant,quantity:1}]});setCartOpen(true)}
  const change=(id:number,delta:number)=>setCart(current=>current.map(i=>i.variant.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0))
  let content; if(path==='/catalog')content=<Catalog products={products} favorites={favorites} onFavorite={favorite}/>; else if(path==='/favorites')content=<Catalog products={products} favorites={favorites} onFavorite={favorite} favoritesOnly/>; else if(path==='/store')content=<StorePage/>; else if(path.startsWith('/product/')){const product=products.find(p=>p.slug===path.split('/').pop());content=product?<ProductPage product={product} favorite={favorites.has(product.id)} onFavorite={favorite} onAdd={add}/>:<div className="not-found"><h1>Товар не найден</h1><button className="button dark" onClick={()=>go('/catalog')}>В каталог</button></div>}else content=<Home products={products} favorites={favorites} onFavorite={favorite}/>
  return <><Header cartCount={cart.reduce((s,i)=>s+i.quantity,0)} favoriteCount={favorites.size} onCart={()=>setCartOpen(true)}/>{content}<Footer/><CartDrawer cart={cart} open={cartOpen} onClose={()=>setCartOpen(false)} onChange={change}/></>
}

export default App
